"""
Abstract base class for all trading strategies.

Provides common interface, utility methods for EV/Kelly calculations,
and position sizing based on bankroll and risk parameters.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        direction: 'BUY' or 'SELL'
        strategy_name: Name of the strategy that generated this signal
        model_probability: Estimated probability of the direction winning (0-1)
        confidence: Signal confidence score (0-1)
        position_size_usd: Recommended position size in USD
        entry_price: Market price at signal generation
        reasoning: Text explanation of the signal
        metadata: Additional strategy-specific data
    """
    direction: str  # 'BUY' or 'SELL'
    strategy_name: str
    model_probability: float
    confidence: float
    position_size_usd: float
    entry_price: float
    reasoning: str
    metadata: Optional[Dict[str, Any]] = None


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement analyze() and should_exit() methods.
    Provides helper methods for EV, Kelly calculation, and position sizing.
    """

    def __init__(self, name: str, settings: Dict[str, Any]):
        """
        Initialize the strategy.

        Args:
            name: Strategy name (e.g., 'momentum', 'mean_reversion')
            settings: Dictionary containing strategy parameters including:
                - kelly_fraction: Fraction of Kelly criterion to use (0-1, default 0.25)
                - max_position_size: Maximum position size in USD
                - min_edge: Minimum expected value to take a trade
                - Any strategy-specific parameters
        """
        self.name = name
        self.settings = settings
        self.kelly_fraction = settings.get('kelly_fraction', 0.25)
        self.max_position_size = settings.get('max_position_size', 1000)
        self.min_edge = settings.get('min_edge', 0.02)  # 2% minimum edge

    @abstractmethod
    def analyze(
        self,
        market: Dict[str, Any],
        orderbook: Dict[str, Any],
        trades: list = None,
        candles: list = None,
        *,
        ticker: str = None,
        recent_trades: list = None,
    ) -> Optional[Signal]:
        """
        Analyze market data and generate a trading signal.

        Args:
            market: Market data including current prices
            orderbook: Current order book state
            trades: Recent trade data (list of trade dictionaries)
            candles: OHLCV candle data (list of candle dictionaries)
            ticker: Market ticker (optional, provided by trader)
            recent_trades: Alias for trades (optional, provided by trader)

        Returns:
            Signal object if a valid signal is generated, None otherwise
        """
        pass

    @abstractmethod
    def should_exit(
        self,
        position: Dict[str, Any],
        market: Dict[str, Any],
        orderbook: Dict[str, Any]
    ) -> bool:
        """
        Determine if an open position should be exited.

        Args:
            position: Current position data including entry price and size
            market: Current market data
            orderbook: Current order book state

        Returns:
            True if position should be exited, False otherwise
        """
        pass

    def calculate_ev(self, model_prob: float, market_price: float) -> float:
        """
        Calculate expected value of a trade.

        For a binary contract:
        - Profit if correct: 1 - market_price
        - Loss if wrong: market_price
        - EV = model_prob * (1 - market_price) - (1 - model_prob) * market_price

        Args:
            model_prob: Model's estimated probability (0-1)
            market_price: Current market price (0-1)

        Returns:
            Expected value as a percentage (0-100 would mean 100% expected return)
        """
        if not (0 <= model_prob <= 1):
            logger.warning(f"model_prob {model_prob} outside valid range [0,1]")
            return 0.0

        if not (0 <= market_price <= 1):
            logger.warning(f"market_price {market_price} outside valid range [0,1]")
            return 0.0

        prob_wrong = 1 - model_prob
        profit = 1 - market_price
        loss = market_price

        ev = model_prob * profit - prob_wrong * loss
        return ev

    def calculate_kelly(self, model_prob: float, market_price: float) -> float:
        """
        Calculate Kelly criterion percentage for position sizing.

        Kelly formula: f* = (b*p - q) / b
        where:
        - p = probability of win (model_prob)
        - q = probability of loss (1 - model_prob)
        - b = payout ratio (profit / loss)

        For binary contracts: profit = 1 - price, loss = price
        b = (1 - market_price) / market_price

        The result is reduced by kelly_fraction to be more conservative.

        Args:
            model_prob: Model's estimated probability (0-1)
            market_price: Current market price (0-1)

        Returns:
            Kelly percentage as fraction of bankroll (0-1), already scaled by kelly_fraction
        """
        if not (0 < market_price < 1):
            logger.warning(f"market_price {market_price} invalid for Kelly calculation")
            return 0.0

        if not (0 < model_prob < 1):
            logger.warning(f"model_prob {model_prob} invalid for Kelly calculation")
            return 0.0

        prob_wrong = 1 - model_prob

        # For binary contracts, payout is 1.0 if you win, 0 if you lose
        # So b = profit / loss = (1 - market_price) / market_price
        b = (1 - market_price) / market_price

        # Kelly formula
        kelly = (b * model_prob - prob_wrong) / b

        # Apply kelly fraction for conservative sizing
        kelly_scaled = kelly * self.kelly_fraction

        # Ensure non-negative result
        return max(0.0, kelly_scaled)

    def calculate_position_size(self, kelly_pct: float, bankroll: float) -> float:
        """
        Calculate position size in dollars based on Kelly percentage and bankroll.

        Position size = kelly_pct * bankroll, capped at max_position_size.

        Args:
            kelly_pct: Kelly percentage as decimal (0-1)
            bankroll: Total available bankroll in USD

        Returns:
            Position size in USD, capped at max_position_size
        """
        if kelly_pct < 0:
            logger.warning(f"kelly_pct {kelly_pct} is negative, returning 0")
            return 0.0

        if bankroll <= 0:
            logger.warning(f"bankroll {bankroll} is non-positive")
            return 0.0

        position_size = kelly_pct * bankroll
        capped_size = min(position_size, self.max_position_size)

        return capped_size
