"""
Data models for Kalshi trading bot.
Includes Market, OrderBook, Order, Position, Trade, Fill, and Signal dataclasses.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Literal


@dataclass
class Market:
    """Represents a Kalshi market."""

    ticker: str
    series_ticker: str
    title: str
    subtitle: str
    yes_price: float
    no_price: float
    volume: float
    open_interest: float
    close_time: int  # Unix timestamp in milliseconds
    status: str  # "open", "closed", "paused", etc.
    result: Optional[str] = None  # "yes", "no", or None if not resolved


@dataclass
class OrderBook:
    """Represents an order book for a market."""

    ticker: str
    yes_bids: List[List[float]] = field(default_factory=list)  # [[price, size], ...]
    yes_asks: List[List[float]] = field(default_factory=list)
    no_bids: List[List[float]] = field(default_factory=list)
    no_asks: List[List[float]] = field(default_factory=list)

    @property
    def best_yes_bid(self) -> Optional[float]:
        """Get the best (highest) bid price for YES contracts."""
        return self.yes_bids[0][0] if self.yes_bids else None

    @property
    def best_yes_ask(self) -> Optional[float]:
        """Get the best (lowest) ask price for YES contracts."""
        return self.yes_asks[0][0] if self.yes_asks else None

    @property
    def best_no_bid(self) -> Optional[float]:
        """Get the best (highest) bid price for NO contracts."""
        return self.no_bids[0][0] if self.no_bids else None

    @property
    def best_no_ask(self) -> Optional[float]:
        """Get the best (lowest) ask price for NO contracts."""
        return self.no_asks[0][0] if self.no_asks else None

    @property
    def yes_spread(self) -> Optional[float]:
        """Get the bid-ask spread for YES contracts."""
        if self.best_yes_bid and self.best_yes_ask:
            return self.best_yes_ask - self.best_yes_bid
        return None

    @property
    def no_spread(self) -> Optional[float]:
        """Get the bid-ask spread for NO contracts."""
        if self.best_no_bid and self.best_no_ask:
            return self.best_no_ask - self.best_no_bid
        return None

    @property
    def yes_midpoint(self) -> Optional[float]:
        """Get the midpoint price for YES contracts."""
        if self.best_yes_bid and self.best_yes_ask:
            return (self.best_yes_bid + self.best_yes_ask) / 2
        return None

    @property
    def no_midpoint(self) -> Optional[float]:
        """Get the midpoint price for NO contracts."""
        if self.best_no_bid and self.best_no_ask:
            return (self.best_no_bid + self.best_no_ask) / 2
        return None


@dataclass
class Order:
    """Represents an order placed on Kalshi."""

    order_id: str
    ticker: str
    side: Literal["yes", "no"]  # Direction: buy YES or buy NO
    type: Literal["limit", "market"]
    price: Optional[float]  # None for market orders
    count: int  # Number of contracts
    status: str  # "pending", "open", "filled", "canceled", etc.
    created_time: int  # Unix timestamp in milliseconds
    expiration_time: Optional[int] = None  # Unix timestamp in milliseconds


@dataclass
class Position:
    """Represents a user position in a market."""

    ticker: str
    market_ticker: str
    count: int  # Positive for long, negative for short
    avg_price: float  # Average entry price
    side: Literal["yes", "no"]  # "yes" if long YES contracts, "no" if long NO
    realized_pnl: float  # Realized profit/loss in USD


@dataclass
class Trade:
    """Represents a completed trade/fill."""

    trade_id: str
    ticker: str
    count: int  # Number of contracts traded
    yes_price: float  # Price at which the trade occurred
    taker_side: Literal["yes", "no"]  # Which side initiated the trade
    created_time: int  # Unix timestamp in milliseconds


@dataclass
class Fill:
    """Represents a fill record for an order."""

    trade_id: str
    order_id: str
    ticker: str
    side: Literal["yes", "no"]
    yes_price: float  # Price of the fill
    count: int  # Number of contracts filled
    created_time: int  # Unix timestamp in milliseconds


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy."""

    strategy_name: str
    ticker: str
    side: Literal["yes", "no"]  # Recommended direction
    confidence: float  # 0-1, how confident in the signal
    model_probability: float  # Model's predicted probability
    market_price: float  # Current market price of YES contracts
    edge: float  # Expected value / edge of the trade
    kelly_fraction: float  # Recommended Kelly fraction sizing
    recommended_size: int  # Number of contracts to trade
    timestamp: datetime
